image:
  tag: "fc24d46f"

replicaCount: 2

resources:
  requests:
    cpu: 40m
    memory: 48Mi
  limits:
    cpu: 125m
    memory: 96Mi

externalDnsHostname: kirui.dev

tls:
  enabled: true
  clusterIssuer: letsencrypt-prod
  secretName: kirui-dev-tls
