image:
  tag: "b87ac40f"

replicaCount: 2

resources:
  requests:
    cpu: 75m
    memory: 48Mi
  limits:
    cpu: 250m
    memory: 192Mi

env:
  DB_HOST: psql-prod-sorcery.postgres.database.azure.com

serviceMonitor:
  enabled: false
