podLabels:
  azure.workload.identity/use: "true"
serviceAccount:
  annotations:
    azure.workload.identity/client-id: "7c3bd8d1-7a36-407a-bbc2-0de085fb0c42"
nodeSelector:
  kubernetes.azure.com/agentpool: main
webhook:
  nodeSelector:
    kubernetes.azure.com/agentpool: main
certController:
  nodeSelector:
    kubernetes.azure.com/agentpool: main
