apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-backup
  namespace: sample-app
  annotations:
    azure.workload.identity/client-id: a8445180-73e4-4675-b3a6-9bfee51616a4
  labels:
    azure.workload.identity/use: "true"
