apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.externalDnsHostname | quote }}
spec:
  selector:
    app: frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
